### PR TITLE
add DMLC_SERVER_ID and DMLC_WORKER_ID to enable Map-Reduce on Workers

### PR DESCRIPTION
**Pull request by jli05**
Add environment variables `DMLC_SERVER_ID` and `DMLC_WORKER_ID` before launching code via `ssh` in order to realise Map-Reduce operations on Workers.

### CODE REVIEW

**Comment by jli05** [comment]
We're doing a project for Prof Anima Anandkumar to implement the Spectral LDA algorithm for MXNet, which starts with Map-Reduce operations on the word count vectors of the document collection. Could we push this PR into `dmlc-core` so that we could proceed?

**Comment by jli05** [comment]
Actually could we revert the merge? I noticed there're fields `mxnet.KVStore.num_workers` and `mxnet.KVStore.rank`. They should suffice for running MapReduce operations.

**Comment by tqchen** [comment]
can you pass a revert PR?

**Comment by jli05** [comment]
I think you may be able to directly do it from here. Let me know otherwise.

https://help.github.com/articles/reverting-a-pull-request/

**Comment by tqchen** [comment]
I cannot directly revert it maybe due to followup changes, please submit a PR to do so

**Pull request merged**
