### PR TITLE
[rabit harden] address subprocess exit deadlock

### PR DESCRIPTION
**Pull request by chenqin**
https://bugs.python.org/issue20318 Caused rabit test hang and timeout from time to time. As python community has no plan to fix in 2.7. We should use process to replace thread to run each rabit worker.

### CODE REVIEW

**Comment by hcho3** [comment]
@chenqin Given that Python 2.x would be EOL end of this year, wouldn't using Python 3 solve the issue?

**Comment by CodingCat** [comment]
yes, and it would be nice if you can help to test xgboost's tracker in python3

**Comment by chenqin** [comment]
python3 seems work on my ubuntu and osx, just confirm, so are we agree to move foward and end support of python2 in next release?

**Comment by hcho3** [comment]
@chenqin @CodingCat I opened a new thread to get votes from the community: #4379. Related: dmlc/tvm#2994

**Comment by CodingCat** [comment]
too many PRs opened and it becomes hard to track which one we should focus on 

close this one as we are moving to py3

**Pull request closed without merging**
