### PR TITLE
 Fix include/dmlc/omp.h for old Android versions

### PR DESCRIPTION
**Pull request by leezu**
https://github.com/dmlc/dmlc-core/pull/582#issuecomment-564334186

### CODE REVIEW

**Comment by hcho3** [comment]
@larroy Can you review?

**Comment by larroy** [comment]
I'm not 100% sure about the logic. Have you guys tried with the MXNet build which uses the NDK? CI is running android builds in mxnet.

**Comment by leezu** [comment]
`__GOMP_NOTHROW` is GNU OpenMP (GCC) specific. So the `__ANDROID__` part of the condition doesn't make sense as you pointed out in https://github.com/dmlc/dmlc-core/pull/582#issuecomment-564334186.

**Comment by larroy** [comment]
Sorry I don't remember this, it's swapped out. If MXNet passes CI with this change I'm fine with it.

**Comment by leezu** [comment]
Tested by https://github.com/apache/incubator-mxnet/pull/17095

**Comment by larroy** [comment]
Then lgtm

**Comment by leezu** [comment]
@hcho3 please help to merge.

**Pull request merged**
