### PR TITLE
add cmake 

### PR DESCRIPTION
**Pull request by yajiedesign**
add cmake file ,Compile with vs2013

### CODE REVIEW

**Comment by tqchen** [comment]
Thanks for the contribution! Please fix the compile and lint errors of travis here https://travis-ci.org/dmlc/dmlc-core/builds/84019619

**Comment by yajiedesign** [comment]
sorry more commit, my epylint not work.

**Comment by tqchen** [comment]
Thanks for the contribution! Can you check what is the difference between lint and lint.py Is it possible that we combine the two and do them in one file?

**Comment by yajiedesign** [comment]
@tqchen you say lint.py and lint3.py?lint.py work in py2 and lint3.py work in py3.

**Comment by tqchen** [comment]
I guess we can make a py2, py3 compatible version of lint, and simply import lint in lint3.py ?

**Comment by tqchen** [comment]
@yajiedesign Just a reminder on this. I think we only need to keep the content in lint3.py rename it to lint.py and use it for both lint in python3 and python3. The code should be compatible in both versions

**Comment by tqchen** [comment]
It would be great if you can submit a PR to update this

**Pull request merged**
