### PR TITLE
Remove throw spec from omp.h for clang

### PR DESCRIPTION
**Pull request by larroy**
This fixes compilation with OMP using the Clang compiler.

### CODE REVIEW

**Comment by hcho3** [comment]
I suspect the memory error is due to race condition

**Comment by larroy** [comment]
@hcho3 in CI ?

**Comment by hcho3** [comment]
@larroy Yes, the memory error you can see in Travis CI is intermittent

**Comment by larroy** [comment]
https://github.com/dmlc/dmlc-core/pull/560

**Comment by larroy** [comment]
https://github.com/dmlc/dmlc-core/pull/559

**Comment by larroy** [comment]
@hcho3 can we merge this? I need it for an MXNet PR.

**Comment by hcho3** [comment]
Merging this for now. I'll create a new issue about failing tests for dmlc_exception and std_exception.

**Comment by larroy** [comment]
seems it's not failing due to double free anymore.

**Comment by leezu** [comment]
@larroy should this be ` #if defined(__ANDROID__) || defined (__clang__)` instead of ` #if defined(__ANDROID__) && defined (__clang__)`. The second doesn't make much sense to me and in fact doesn't work with clang

**Comment by larroy** [comment]
I think the intention was to fix it for Android only, when using clang, hence &&, don't remember the details. But see that we are compiling with Clang in CI for a while, why did it start failing now?

**Pull request merged**
