### PR TITLE
Upgrade Google Test to 1.10.0

### PR DESCRIPTION
**Pull request by rongou**
The main change is the renaming of `...TestCase` to `...TestSuite`.

@hcho3

### CODE REVIEW

**Comment by hcho3** [comment]
@rongou Just curious, what are some tangible benefits that you like about GTest 1.10.0?

**Comment by rongou** [comment]
As I mentioned above, it renames *TestCase methods to *TestSuite, so code using these methods would be more future proof with this version.

**Comment by comaniac** [comment]
Thanks @rongou @hcho3 @terrytangyuan, this is now merged.

**Comment by leezu** [comment]
CI often fails with googletest related issues now.

For example 

```
In

 file included from googletest/include/gtest/gtest-matchers.h:47:0,

                 from googletest/include/gtest/internal/gtest-death-test-internal.h:39,

                 from googletest/include/gtest/gtest-death-test.h:41,

                 from googletest/include/gtest/gtest.h:64,

                 from googletest/src/gtest-all.cc:38:

googletest/include/gtest/gtest-printers.h: In instantiation of ‘void testing::internal::PrintTo(const T&, std::ostream*) [with T = long long int; std::ostream = std::basic_ostream<char>]’:

googletest/include/gtest/gtest-printers.h:679:22:   required from ‘static void testing::internal::UniversalPrinter<T>::Print(const T&, std::ostream*) [with T = long long int; std::ostream = std::basic_ostream<char>]’

googletest/include/gtest/gtest-printers.h:869:40:   required from ‘void testing::internal::UniversalPrint(const T&, std::ostream*) [with T = long long int; std::ostream = std::basic_ostream<char>]’

googletest/include/gtest/gtest-printers.h:797:29:   required from ‘static void testing::internal::UniversalTersePrinter<T>::Print(const T&, std::ostream*) [with T = long long int; std::ostream = std::basic_ostream<char>]’

googletest/include/gtest/gtest-printers.h:917:55:   required from ‘std::string testing::PrintToString(const T&) [with T = long long int; std::string = std::basic_string<char>]’

googletest/include/gtest/gtest-printers.h:314:42:   required from ‘static std::string testing::internal::FormatForComparison<ToPrint, OtherOperand>::Format(const ToPrint&) [with ToPrint = long long int; OtherOperand = long long int; std::string = std::basic_string<char>]’

googletest/include/gtest/gtest-printers.h:379:51:   required from ‘std::string testing::internal::FormatForComparisonFailureMessage(const T1&, const T2&) [with T1 = long long int; T2 = long long int; std::string = std::basic_string<char>]’

googletest/src/gtest.cc:1454:62:   required from here

googletest/include/gtest/gtest-printers.h:506:15: error: ‘value’ is not a member of ‘testing::internal::IsRecursiveContainer<long long int>’

               !IsRecursiveContainer<T>::value

               ^

ar -rv libgtest.a gtest/gtest-all.o

ar: creating libgtest.a

ar: gtest/gtest-all.o: No such file or directory

scripts/packages.mk:8: recipe for target '/home/travis/.cache/usr/include/gtest' failed
```

https://travis-ci.org/dmlc/dmlc-core/jobs/659370538?utm_medium=notification&utm_source=github_status

Did this happen before upgrade to 1.10 @comaniac @terrytangyuan? If not, can you look into fixing the issue?

**Pull request merged**
