### PR TITLE
[Bugfix] Fix logging tests

### PR DESCRIPTION
**Pull request by junrushao1994**
Hope this could pass the unittests :-)

@hcho3 @tqchen

### CODE REVIEW

**Comment by junrushao1994** [comment]
Looks like MSVC 2013 doesn't recognize `thread_local`

**Comment by tqchen** [comment]
Let us just disable msvc 2013 in here https://github.com/dmlc/dmlc-core/blob/master/appveyor.yml

**Comment by hcho3** [comment]
Yes, let's drop MSVC 2013, since dmlc-core has been upgraded to C++11 standard. We need MSVC 2015+ to compile C++11.

**Comment by junrushao1994** [comment]
Thank you @hcho3 and @tqchen!

**Pull request merged**
