### PR TITLE
fix tracker for python 3.9

### PR DESCRIPTION
**Pull request by rongou**
Python 3.9 removed the deprecated method `Thread.isAlive` and replace it with `Thread.is_alive`.

See https://bugs.python.org/issue37804

### CODE REVIEW

**Comment by rongou** [comment]
@hcho3 @trivialfis

**Comment by trivialfis** [comment]
I think XGBoost is no longer using the tracker in dmlc-core.

**Comment by rongou** [comment]
It's still used in the distributed tests: https://github.com/dmlc/xgboost/blob/master/tests/distributed/runtests.sh#L7

**Comment by trivialfis** [comment]
We can copy the submit script into XGBoost as well, otherwise, there are two trackers in use.  The fix looks good to me, @hcho3 can help merge it

**Pull request merged**
