### PR TITLE
update strtonum

### PR DESCRIPTION
**Pull request by krishnap25**
Updated strtonum to work with unsigned long long

### CODE REVIEW

**Comment by tqchen** [comment]
@mli  can you look into this? There is an interesting issue about unsigned long long, that makes some of things break in certain platform. It should have been covered by uint64_t. I am not sure why this specialization is needed  here.

**Comment by mli** [comment]
hi Krishna, 

this is due to gcc4.8's bug. please make a pull for ps-lite, or follow this commit:

https://github.com/dmlc/ps-lite/commit/a47fe951c55a089efadb6ae8df866aa3fe031f8a

adding Str2T<unsigned long long> will leads to compilation failure on recent gcc and clang.

**Comment by krishnap25** [comment]
I'm getting the same bug even though I use gcc 4.9.1 and 4.9.2, and use the
latest commit of ps-lite. What do I do now?

One alternative is to guard Str2T using the __GNUC__ macro.

-Krishna Pillutla

**Comment by mli** [comment]
the bug is due to some compilers think `unsigned long long` and `uint64_t` are different types, but the others think they are the same one. dmlc-core uses uint64_t, so you may change your codes to follow this conversion.

**Pull request closed without merging**
