### PR TITLE
Fix dmlc::strtof()

### LINKED ISSUE #478: Fixes recently introduced error with _create_locale and msvcrt
<details>
<summary>The patch</summary>

```patch
From a0b0f7622df29b176a7165c1719037d9c23d66e4 Mon Sep 17 00:00:00 2001
From: KOLANICH <KOLANICH@user.noreply.github.com,>
Date: Tue, 6 Nov 2018 19:55:46 +0300
Subject: [PATCH] Fixed the error with _create_locale by changing the dll for
 stdlib for MinGW-W64.

---
 .gitignore                                    |  1 +
 CMakeLists.txt                                |  8 +++++
 .../workaround_MinGW_MSVCRT_to_MSVCR100.cmake | 33 +++++++++++++++++++
 ...ound_MinGW_MSVCRT_to_MSVCR100_script.cmake |  9 +++++
 test/unittest/CMakeLists.txt                  |  7 ++++
 5 files changed, 58 insertions(+)
 create mode 100644 cmake/workaround_MinGW_MSVCRT_to_MSVCR100.cmake
 create mode 100644 cmake/workaround_MinGW_MSVCRT_to_MSVCR100_script.cmake

diff --git a/.gitignore b/.gitignore
index 707d9ff..c8a77b3 100644
--- a/.gitignore
+++ b/.gitignore
@@ -47,3 +47,4 @@ build
 .idea
 cmake-build-*
 /include/dmlc/build_config.h
+/withMSVCR100.spec
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ea9f659..62cb6b1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -202,6 +202,14 @@ target_link_libraries(dmlc ${dmlccore_LINKER_LIBS})
 target_compile_definitions(dmlc PRIVATE -D_XOPEN_SOURCE=700
   -D_POSIX_SOURCE -D_POSIX_C_SOURCE=200809L -D_DARWIN_C_SOURCE)
 
+if(WIN32)
+  if(MSVC)
+  else(MSVC)
+    if(DMLC_CREATE_LOCALE_PRESENT)
+      include(cmake/workaround_MinGW_MSVCRT_to_MSVCR100.cmake)
+      workaround_MinGW_MSVCRT_to_MSVCR100(dmlc)
+    endif(DMLC_CREATE_LOCALE_PRESENT)
+  endif(MSVC)
+endif(WIN32)
+
 # ---[ Install Includes
 if(INSTALL_INCLUDE_DIR)
   add_custom_command(TARGET dmlc POST_BUILD
diff --git a/cmake/workaround_MinGW_MSVCRT_to_MSVCR100.cmake b/cmake/workaround_MinGW_MSVCRT_to_MSVCR100.cmake
new file mode 100644
index 0000000..cd7c1b7
--- /dev/null
+++ b/cmake/workaround_MinGW_MSVCRT_to_MSVCR100.cmake
@@ -0,0 +1,33 @@
+﻿# 2018-11-06 Licensed under Unlicense https://unlicense.org/
+# Workarounds a flaw in MinGW-W64 using old msvcrt.dll without some functions somewhen needed.
+# Inspired by https://gitweb.torproject.org/builders/tor-browser-bundle.git/tree/gitian/descriptors/windows/gitian-utils.yml?id=b273e8a38b24e716008fa9f51a2b53f20c1f1255#n92 .
+# Unfortunately MinGW-w64 devs like Sourceforge more than getting bug reports and/or pull requests.
+
+set(SCRIPT_FILE_NAME "${CMAKE_CURRENT_LIST_DIR}/workaround_MinGW_MSVCRT_to_MSVCR100_script.cmake")
+set(funcName "workaround_MinGW_MSVCRT_to_MSVCR100")
+
+function("${funcName}" target)
+  set(additionalTargetName "workaroundMSVCR100")
+  
+  message(WARNING "${funcName} was used on target \"${target}\". It should be used on dependent targets using that as a native library too, otherwise crashes are likely.")
+  
+  if (TARGET ${additionalTargetName})
+  else()
+    message(STATUS "specFileName is empty")
+    set(specFileName "${CMAKE_BINARY_DIR}/specsWithMSVCR100.spec" CACHE FILENAME "Stores specs" FORCE)
+    add_custom_command(
+      PRE_BUILD
+      OUTPUT "${specFileName}"
+      COMMAND "${CMAKE_COMMAND}" "-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}" "-DspecFileName=${specFileName}" -P ${SCRIPT_FILE_NAME}
+      COMMENT "Generating specs into ${specFileName}"
+    )
+    add_custom_target("${additionalTargetName}" DEPENDS "${specFileName}")
+  endif()
+  
+  set_property(
+    TARGET "${target}"
+    APPEND PROPERTY
+      LINK_FLAGS "-specs=${specFileName}"
+  )
+  add_dependencies("${target}" "${additionalTargetName}")
+endfunction()
diff --git a/cmake/workaround_MinGW_MSVCRT_to_MSVCR100_script.cmake b/cmake/workaround_MinGW_MSVCRT_to_MSVCR100_script.cmake
new file mode 100644
index 0000000..802aca0
--- /dev/null
+++ b/cmake/workaround_MinGW_MSVCRT_to_MSVCR100_script.cmake
@@ -0,0 +1,9 @@
+# 2018-11-06 Licensed under Unlicense https://unlicense.org/
+
+execute_process(
+  COMMAND "${CMAKE_CXX_COMPILER}" "-dumpspecs"
+  RESULT_VARIABLE SUCCESS
+  OUTPUT_VARIABLE SPECS
+)
+string(REPLACE "msvcrt" "msvcr100" SPECS "${SPECS}")
+file(WRITE "${specFileName}" "${SPECS}")
diff --git a/test/unittest/CMakeLists.txt b/test/unittest/CMakeLists.txt
index b5339fe..952dbd8 100644
--- a/test/unittest/CMakeLists.txt
+++ b/test/unittest/CMakeLists.txt
@@ -62,3 +62,10 @@ else()
 endif()
 
 add_test(AllTestsInDMLCUnitTests ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/dmlc_unit_tests)
+
+if(WIN32)
+  if(MSVC)
+  else(MSVC)
+    if(DMLC_CREATE_LOCALE_PRESENT)
+      workaround_MinGW_MSVCRT_to_MSVCR100(dmlc_unit_tests)
+    endif(DMLC_CREATE_LOCALE_PRESENT)
+  endif(MSVC)
+endif(WIN32)
+
-- 
2.19.1.windows.1
```
</details>

### PR DESCRIPTION
**Pull request by hcho3**
Previous implementation of locale-independent parsing (#455) was faulty:
1. It broke builds for MinGW-w64 + Windows 7 target (#478)
2. It doesn't parse 0 correctly (https://github.com/dmlc/dmlc-core/pull/455#issuecomment-436814655).
3. The use of locale functions adds too much complexity, which goes against the spirit of dmlc-core as basic building blocks.

This PR rectifies the situation by re-using existing implementation of `strtof()`. In particular,
1. `dmlc::data::strtof()` is moved to `include/` directory.
2. Add template parameters to the `strtof()` implementation to add range checking and to implement `dmlc::strtod()`.
3. Add a better test for float parameter parsing.

Also, the locale functions have been removed.

Closes #478.

### CODE REVIEW

**Comment by hcho3** [comment]
@trivialfis I've removed platform-dependent code for the sake of future maintenance burden.

**Comment by hcho3** [comment]
TODO. Add docstrings for all public functions in `include/dmlc/strtonum.h`.

**Comment by KOLANICH** [comment]
Works fine, thank you.

**Comment by hcho3** [comment]
@KOLANICH Glad it solved your problem.

TODO: use [libc-test](https://github.com/AssemblyScript/libc-test) to rigorously test `dmlc::strtof()` and `dmlc::strtod()`.

**Pull request merged**
