### PR TITLE
fix bug when use path_imgidx in ImageRecordIter

### PR DESCRIPTION
**Pull request by solin319**
When use ImageRecordIter read data set on S3, use std::ifstream to read idx file on S3 will cause segment fault.
Can we change it to dmlc::Stream created by fs->Open.
@tqchen

### CODE REVIEW

**Comment by tqchen** [comment]
We can, but we will need to close it or wrap the dmlc::Stream in std::unique_ptr

**Comment by solin319** [comment]
We have wrapped the dmlc::Stream in std::unique_ptr.

**Comment by solin319** [comment]
@tqchen

**Comment by tqchen** [comment]
Thanks for the contribution, this is merged

**Pull request merged**
