### PR TITLE
Define `omp_in_parallel` stub.

### PR DESCRIPTION
**Pull request by trivialfis**
Related issue: https://github.com/dmlc/xgboost/issues/5518

### CODE REVIEW

**Comment by trivialfis** [comment]
@hcho3 Is this a flaky test on Windows?

```
[----------] 1 test from Logging
[ RUN      ] Logging.basics
[14:28:58] C:/projects/dmlc-core/test/unittest/unittest_logging.cc:8: hello
[14:28:58] C:/projects/dmlc-core/test/unittest/unittest_logging.cc:9: error
C:/projects/dmlc-core/test/unittest/unittest_logging.cc:18: Failure
Death test: if (dmlc::LogCheckError _check_err = dmlc::LogCheck_NE(x, y)) dmlc::LogMessageFatal("C:/projects/dmlc-core/test/unittest/unittest_logging.cc", 18).stream() << "Check failed: " << "x" " " "!=" " " "y" << *(_check_err.str) << ": "
    Result: died but not with expected exit code:
            Exited with exit status 0
Actual msg:
[  DEATH   ] [14:28:58] C:/projects/dmlc-core/test/unittest/unittest_logging.cc:8: hello
[  DEATH   ] [14:28:58] C:/projects/dmlc-core/test/unittest/unittest_logging.cc:9: error
[  DEATH   ] 
[  FAILED  ] Logging.basics (123 ms)
[----------] 1 test from Logging (123 ms total)
[----------] 2 tests from Lockfree

```

**Comment by hcho3** [comment]
@trivialfis Try re-running it?

**Comment by trivialfis** [comment]
@hcho3 It seems I triggered some hidden bug in logging.

**Comment by hcho3** [comment]
Can you rebase this against latest master?

**Comment by trivialfis** [comment]
@hcho3  Done.

**Pull request merged**
