### PR TITLE
std::chrono in timer.h

### PR DESCRIPTION
**Pull request by WojciechMigda**
Retrieve current timestamp with std::chrono API.

### CODE REVIEW

**Comment by WojciechMigda** [comment]
sorry, it was meant for my fork

**Comment by tqchen** [comment]
This was actually a good PR, I think I am going to merge this in

**Comment by tqchen** [comment]
It would be great if you can help squash and fix the lint error

**Comment by WojciechMigda** [comment]
Oh, but please double check if this is what you'd expect to have here. I didn't spend significant amount of time trying to understand the context where these timings are used for and this is simply stub I used for topcoder. I have neither analysed the hierarchy of #defines and correctness on win platforms. Do you have that covered in your testing environment?
I'll have a look into the lint error in the meantime.

**Comment by tqchen** [comment]
I see, it is only used to get relative timing, so the chrono is fine. would be nice if you can submit a separate PR just for the timer, but no hurries

**Comment by WojciechMigda** [comment]
Lint is complaining about the header order? If so, how do you enforce that `DMLC_USE_CXX11` is `#defined` before conditional `<chrono>` inclusion occurs if local headers cannot appear before the system ones?

**Comment by tqchen** [comment]
I think rabit's Timer is less frequently used and will be eventually switch to dmlc's timer so we are fine there

**Pull request closed without merging**
