### PR TITLE
GetCurrentThreadId() call needs windows.h

### PR DESCRIPTION
**Pull request by cjolivier01**

### CODE REVIEW

**Comment by tqchen** [comment]
why not use http://en.cppreference.com/w/cpp/thread/get_id?

**Comment by cjolivier01** [comment]
This is a 3rd-party optimized lockfree queue. It has some specialized code for different platforms for one reason or another. I am not comfortable changing that code since I assume it's like that for a reason.

**Comment by tqchen** [comment]
OK, I would normally take caution in simply including code into codebase without being able to maintain it. But assuming the moodycamel queue is stable for a while, we might be able to do that, periodically check with upstream is needed

**Comment by cjolivier01** [comment]
ok

**Comment by cjolivier01** [comment]
It'd be better if we could use boost, but that's been outlawed from what I understand :)

**Comment by tqchen** [comment]
as far as I understand, moodycamel queue performs better than boost.lockfree

**Comment by cjolivier01** [comment]
Yeah, they actually don't even use atomics for the simple operations. They sort of work like JEMalloc, where each thread gets its own little section of memory.

**Comment by tqchen** [comment]
Yes, thread local memory management is a common trick for doing things right. We will need to see through on how things can or cannot be improved. While lockfree increases the concurrency, our previous experience find the extra spin sometimes will throttle the CPUs

**Comment by cjolivier01** [comment]
The blocking queue does some spinning, but the reqular, non-blocking queue doesn't. I plan to mostly use the regular one for stuff like pushing profiling data to the profiler (have a PR for that up and some other work going on with it).  I agree the affects of using the blocking queue should be understood and tuned to its specific purpose so as not to starve CPU from other threads.

**Comment by tqchen** [comment]
The non-blocking version requires user to do the spinning actually and need user to poll over multiple queues, a wait mechanism is still needed

**Comment by cjolivier01** [comment]
Depends how you use it.  For DumpProfile(), for instance, the queue is just emptied and then the procedure is over.  There's no reason to block, spin, or otherwise wait for more data.  If you need to wait for more data, then might as well use a blocking queue of some sort.

**Pull request merged**
