### PR TITLE
Add Kubernetes tracker

### PR DESCRIPTION
**Pull request by YujiOshima**
You can submit distributed tasks to Kubernetes.
Related to https://github.com/apache/incubator-mxnet/issues/4103.

```
dmlc-submit \
    --cluster kubernetes \
    --jobname test \
    --num-workers 3 \
    --num-server 1 \
    --kube-worker-image yujioshima/mxnet \
    --kube-server-image yujioshima/mxnet \
    python /incubator-mxnet/example/image-classification/train_cifar10.py --network=resnet --num-layers=110 --batch-size=128 --kv-store=dist_device_sync
```

If you want to more detail config for kubernetes, you can use a manifest template.

```
./dmlc-core/tracker/dmlc-submit \
    --cluster kubernetes \
    --jobname test \
    --num-workers 4 \
    --num-server 1 \
    --kube-worker-image yujioshima/mxnet:gpu \
    --kube-server-image yujioshima/mxnet \
    --kube-server-template mxnet-docker/manifests/jobs/ps.yml \
    --kube-worker-template worker.yml \
    python /incubator-mxnet/example/image-classification/train_cifar10.py --network=resnet --num-layers=110 --batch-size=128 --kv-store=dist_device_sync
```

Signed-off-by: YujiOshima <yuji.oshima0x3fd@gmail.com>

### CODE REVIEW

**Comment by zhangbin-intellif** [comment]
@YujiOshima I cannot slove the problem below, thank you for any useful advices.
I use this command(I have installed kubernetes cluster with one node):
`/home/zb/KubeZb/incubator-mxnet/dmlc-core/tracker/dmlc-submit \
    --cluster kubernetes \
    --jobname test \
    --num-workers 1 \
    --num-server 1 \
    --kube-worker-image mxnet-gpu-dst \
    --kube-server-image mxnet-cpu-dst \
    --kube-server-template mx-server.yaml \
    --kube-worker-template mx-worker.yaml \
    python /incubator-mxnet/example/image-classification/train_mnist.py --network lenet --gpus 0 --kv-store dist_device_sync`

**and I got following error on creating sheduler job:**
`[05:28:10] src/van.cc:75: Bind to role=scheduler, id=1, ip=mx-test-sched, port=-1, is_recovery=0
[05:28:10] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [05:28:10] src/van.cc:76: Check failed: (my_node_.port) != (-1) bind failed
 Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x17c44c) [0x7f740df2f44c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x2905ff1) [0x7f74106b8ff1]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x290fc4a) [0x7f74106c2c4a]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x28ff53b) [0x7f74106b253b]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x24b32ed) [0x7f74102662ed]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXKVStoreRunServer+0x72) [0x7f741008f502]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f74289f8e40]
[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f74289f88ab]
[bt] (8) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f7428c083df]
[bt] (9) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f7428c0cd82]
 Traceback (most recent call last):
  File "/incubator-mxnet/example/image-classification/train_mnist.py", line 25, in <module>
    from common import find_mxnet, fit
  File "/incubator-mxnet/example/image-classification/common/find_mxnet.py", line 20, in <module>
    import mxnet as mx
  File "/usr/local/lib/python2.7/dist-packages/mxnet/__init__.py", line 56, in <module>
    from . import kvstore_server
  File "/usr/local/lib/python2.7/dist-packages/mxnet/kvstore_server.py", line 85, in <module>
    _init_kvstore_server_module()
  File "/usr/local/lib/python2.7/dist-packages/mxnet/kvstore_server.py", line 82, in _init_kvstore_server_module
    server.run()
  File "/usr/local/lib/python2.7/dist-packages/mxnet/kvstore_server.py", line 73, in run
    check_call(_LIB.MXKVStoreRunServer(self.handle, _ctrl_proto(self._controller()), None))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [05:28:10] src/van.cc:76: Check failed: (my_node_.port) != (-1) bind failed
 Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x17c44c) [0x7f740df2f44c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x2905ff1) [0x7f74106b8ff1]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x290fc4a) [0x7f74106c2c4a]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x28ff53b) [0x7f74106b253b]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x24b32ed) [0x7f74102662ed]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXKVStoreRunServer+0x72) [0x7f741008f502]
[bt] (6) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f74289f8e40]
[bt] (7) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f74289f88ab]
[bt] (8) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f7428c083df]
[bt] (9) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f7428c0cd82`

**and my kubernetes cluster status as follows:**
image

**Comment by YujiOshima** [comment]
@zhangbin-intellif I have not seen that error. 
If you can, Please show your template yaml files for server and worker.

**Comment by zhangbin-intellif** [comment]
@YujiOshima  Thanks for your reply. I may have solved this problem by modify incubator-mxnet/ps-lite/src/van.cc, and I rebuild my cpu version docker image"mxnet-cpu-dst"
```
void Van::Start() {
    .....
    if (is_scheduler_) {
        
        my_node_ = scheduler_;
        std::string ip; 
        const char*  itf = Environment::Get()->find("DMLC_INTERFACE");
        std::string interface;
        if (itf) interface = std::string(itf);
        if (interface.size()) {
          GetIP(interface, &ip);
        } else {
          GetAvailableInterfaceAndIP(&interface, &ip);
        }
        my_node_.hostname = ip; 
        .......
   }
```
**and the training still cannot run successfully, but the errors before didnot reappear. The new problem is 
the scheduler and server job run a few second and completed, the worker job donnot show any logs or errors. the only info is the worker pod container restart once. The kubernetes node info , server.yaml and worker.yaml are as follows**
image

  server.yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: mx-dst
spec:
  template:
    metadata:
      labels:
        app: mx-dst
    spec:
      volumes:
      - hostPath:
          path: /home/zb/KubeZb/docker-files/incubator-mxnet
        name: incubator-mxnet
      containers:
      - name: mx-dst
        image: mx-cpu-test
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /incubator-mxnet
          name: incubator-mxnet
      restartPolicy: OnFailure
```

worker.yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: mx-dst
spec:
  template:
    metadata:
      labels:
        app: mx-dst
    spec:
      volumes:
      - hostPath:
          path: /usr/lib/nvidia-384/bin
        name: bin
      - hostPath:
          path: /usr/lib/nvidia-384
        name: lib
      - hostPath:
          path: /usr/lib/x86_64-linux-gnu/libcuda.so
        name: libcuda-so
      - hostPath:
          path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
        name: libcuda-so-1
      - hostPath:
          path: /usr/lib/x86_64-linux-gnu/libcuda.so.384.90
        name: libcuda-so-384-90
      - hostPath:
          path: /usr/local/cuda/lib64/libcusolver.so
        name: libcusolver-so
      - hostPath:
          path: /usr/local/cuda/lib64/libcusolver.so.9.0
        name: libcusolver-so-9-0
      - hostPath:
          path: /usr/local/cuda/lib64/libcusolver.so.9.0.176
        name: libcusolver-so-9-0-176
      - hostPath:
          path: /usr/lib/x86_64-linux-gnu/libnccl.so
        name: libnccl-so
      - hostPath:
          path: /usr/lib/x86_64-linux-gnu/libnccl.so.2
        name: libnccl-so-2
      - hostPath:
          path: /usr/lib/x86_64-linux-gnu/libnccl.so.2.1.2
        name: libnccl-so-2-1-2
      - hostPath:
          path: /home/zb/KubeZb/docker-files/incubator-mxnet
        name: incubator-mxnet
      containers:
      - name: mx-dst
        image: mx-gpu-test
        imagePullPolicy: Never
        env:
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/local/nvidia/lib
          name: lib
        - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
          name: libcuda-so
        - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
          name: libcuda-so-1
        - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.384.90
          name: libcuda-so-384-90
        - mountPath: /usr/local/nvidia/lib/libcusolver.so
          name: libcusolver-so
        - mountPath: /usr/local/nvidia/lib/libcusolver.so.9.0
          name: libcusolver-so-9-0
        - mountPath: /usr/local/nvidia/lib/libcusolver.so.9.0.176
          name: libcusolver-so-9-0-176
        - mountPath: /usr/lib/x86_64-linux-gnu/libnccl.so
          name: libnccl-so
        - mountPath: /usr/lib/x86_64-linux-gnu/libnccl.so.2
          name: libnccl-so-2
        - mountPath: /usr/lib/x86_64-linux-gnu/libnccl.so.2.1.2
          name: libnccl-so-2-1-2
        - mountPath: /incubator-mxnet
          name: incubator-mxnet
      restartPolicy: OnFailure
```
**I just cannot figure out what resulted in this problem, any ideas or advice are appreciated!!!**

**Comment by GoodJoey** [comment]
@YujiOshima  i can create the job through the tracker? is there any way i can stop the job?

**Comment by GoodJoey** [comment]
@YujiOshima 
hi，where can i download the template files, work.yml and ps.yml?
and if i run it on k8s cluster, how does the contains know it's working with others?

**Comment by YujiOshima** [comment]
@GoodJoey 
Hi! There is no sample of the template files. You don't need template files if you won't use GPUs or PVCs etc. 
When you want to set up a specific configuration for your environment,  you should prepare your template Kubernetes manifest files which has GPU resources or PVC paths etc.
The k8s tracker will rewrite the names, container images, commands and envs of the template files.
And you can get the state of jobs by using the `kubectl` command e.g. `kubectl get jobs`, `kubectl logs job/test-job-worker1`.

**Comment by GoodJoey** [comment]
@YujiOshima 
Thanks for your response.
for the second question, i meant, in your sample, you start 3 workers.
how do the 3 workers communicate with each other, how do the 3 workers 'split' the training job?
it seems they download the train data in their own containers, and generate the models in their own containers.

**Comment by YujiOshima** [comment]
@GoodJoey OK, I understand. It depends on DL flamework. In my sample MxNet, the scheduler pod manages the communication and train data.  So k8s tracker will create some server pods, worker pods, and one scheduler pod. Servers and workers will get the address of scheduler with environment value `DMLC_PS_ROOT_URI` and `DMLC_PS_ROOT_PORT`.

You should use `kubectl` command to delete train jobs. I think the dmlc-core tracker doesn't have CLIs for deletion.

**Comment by GoodJoey** [comment]
@YujiOshima 
thanks.
right, i look into the code, and see the DMLC_PS_ROOT_URI and DMLC_PS_ROOT_PORT.
but in my k8s, zmq_bind can't bind to the DMLC_PS_ROOT_URI for the schduler.
it always gets the error, src/van.cc:76: Check failed: (my_node_.port) != (-1) bind failed
the DMLC_PS_ROOT_URI and DMLC_PS_ROOT_URI  seems right, which is mx-test-sched:9091,
but it's always failed binding, so weird. 
Maybe it's because my kubernetes' version? mine is 1.9.

**Comment by GoodJoey** [comment]
@zhangbin-intellif 
i see when you fix the bind issue, you tried to get the ip of scheduler instead of hostname, but are u sure the ip  is right?
and have you solved the issues, can run the mxnet on k8s successfully? thanks

**Comment by zhangbin-intellif** [comment]
@GoodJoey 
I tried to get the ip of scheduler instead of hostname,the node port binding problem does not appear again, but I'm not sure if worker, server and scheduler can communicate correctly, because my distributed training not started. The container logs of worker,server and scheduler shows that they can find each other,but the training just can not be started, I'm now blocked by this problem. Have you solved the problem?

**Comment by zhangbin-intellif** [comment]
@GoodJoey the problem was solved now，just use  the ip of scheduler，it all works！

**Comment by GoodJoey** [comment]
@zhangbin-intellif 
are you testing on VM or local nodes? did u create your cluster using kubeadm?
can i chat with you through QQ, mine is 2238766453

**Pull request merged**
