### PR TITLE
Refactor CmakeLists.txt to avoid global variables

### PR DESCRIPTION
**Pull request by leezu**
Fixes crosscompilation for Android NDK 19+

Need to resubmit this PR many times as AppVeyor is broken and stuck at "Queued" state.

### CODE REVIEW

**Comment by hcho3** [comment]
@leezu It would be nice to dump AppVeyor and use Azure Pipelines or GitHub actions, both of which support parallel jobs.

**Comment by leezu** [comment]
Previously the build is stuck for more than 30 minutes. I don't think there was any parallel build going that would justify the queue. Supposedly there should be no issue: https://status.appveyor.com/

**Comment by hcho3** [comment]
@leezu In fact, dmlc-core shared build queue with XGBoost, so PRs in XGBoost are blocking your PR. Hence my comment about parallel jobs.

**Comment by hcho3** [comment]
Let me clarify here a bit. All PRs in dmlc-core and xgboost generate multiple jobs, and these jobs all get enqueued to a single queue, and AppVeyor runs only one job at a time. This is why you see a backlog.

**Comment by leezu** [comment]
Thanks @hcho3. Please merge.

**Pull request merged**
