### PR TITLE
[python3] use python3 dmlc tracker in rabit tests

### PR DESCRIPTION
**Pull request by chenqin**
upgrade to dmlc-submit to python3 as alternative to https://github.com/dmlc/dmlc-core/pull/524

### CODE REVIEW

**Comment by chenqin** [comment]
https://github.com/dmlc/xgboost/issues/4379

**Comment by CodingCat** [comment]
how we verify python3 can make rabit test pass?

**Comment by chenqin** [comment]
I tested in my local OS X and Linux, to have Travis chi working we need to get either this or deadlock or in and git update sub module

**Comment by CodingCat** [comment]
as the common practice like before, we should point rabit to the private branch having python 3 to verify  

and 

there are still bunch of places in the code base using python instead of python3, we'd fix in one shot instead of leaving code base in an inconsistent status using py2 and py3 simultaneously

**Comment by chenqin** [comment]
This is getting convoluted, if we need to fix rabit problem do we need to wait all xgboost upgrade to python3? Otherwise, we should merge https://github.com/dmlc/dmlc-core/pull/524 and keep upgrade python3 in parallel

**Comment by CodingCat** [comment]
>  if we need to fix rabit problem do we need to wait all xgboost upgrade to python3?

make a simple search, https://github.com/dmlc/dmlc-core/search?l=Python&q=python  

> Otherwise

otherwise against what? 

> we should merge #524 

alternatives as highlighted

image

**Comment by chenqin** [comment]
524 assume we support python2 and python3 
525 meant to drop support of python2 and assume deadlock issue go away with python2

unless we can assume https://github.com/dmlc/xgboost/tree/master/python-package/xgboost works with python3, python3 upgrade might be more than we expected.  Ultimately, my impression is we should get away all python2 packages from pip install and move to pip3.

**Comment by CodingCat** [comment]
> unless we can assume https://github.com/dmlc/xgboost/tree/master/python-package/xgboost works with python3, python3 upgrade might be more than we expected. 

it is not related to what we are talking about here, and if you have any concern or you think you find some cases XGBoost cannot move forward to py3, please stated in https://github.com/dmlc/xgboost/issues/4379

> Ultimately, my impression is we should get away all python2 packages from pip install and move to pip3.

yes, that's why I said, if you want to upgrade to python 3 in this code base, you'd upgrade everything appeared in https://github.com/dmlc/dmlc-core/search?l=Python&q=python

**Comment by hcho3** [comment]
@chenqin FYI, XGBoost has been tested with Python 3 for a good while.

**Pull request merged**
