### PR TITLE
Add OpenMP as CMake target

### PR DESCRIPTION
**Pull request by hcho3**
Simplify logic for importing OpenMP into the CMake build by treating OpenMP as a target. This way, we no longer have to set compiler flags to enable OpenMP. See https://cliutils.gitlab.io/modern-cmake/chapters/packages/OpenMP.html for more information.

@dmlc/dmlc-core-committer @trivialfis Please help review. This will be especially useful for Mac OSX users. The old way requires them to use Homebrew GCC, which is a heavy dependency (*). The new way allows them to use Apple Clang (default system compiler) instead. 

(*) See discussion at https://github.com/Homebrew/homebrew-core/pull/43246, where Homebrew maintainers asked to remove GCC dependency from XGBoost.

### CODE REVIEW

**Comment by hcho3** [comment]
Sorry for the noise. I'm now done ironing out all loose ends. This PR is now ready for review.

**Comment by hcho3** [comment]
@trivialfis Do you mean that we should remove unittest_gtest for OSX?

**Comment by trivialfis** [comment]
@hcho3 No.  I see package `gcc@7` is removed, so we are no-longer testing dmlc-core compiled with gcc on OSX.  Just curious whether the test is required for dmlc-core.

**Comment by hcho3** [comment]
@trivialfis I put back gcc. Now dmlc-core is tested against both gcc and Apple Clang.

**Comment by hcho3** [comment]
@larroy

**Comment by larroy** [comment]
sorry I missed this LGTM

**Pull request merged**
