### PR TITLE
Update yarn.py

### PR DESCRIPTION
**Pull request by wendycwong**
Two bugs discovered by Michal M.

### CODE REVIEW

**Comment by wendycwong** [comment]
I was trying to run xgboost 0.82 off hadoop/yarn.  It needs to use python3 specified in kubernetes.py.  

[1]+  Exit 1                  nohup ./dmlc-submit --cluster=yarn --num-workers=4 --worker-memory='50g' /home/wendy/xgboost_reproducibility/xgboost/xgboost higgs_all.aws.conf > HiggsRun1
(wendy_env_35) wendy@mr-0xd2:~/xgboost_reproducibility/xgboost/dmlc-core/tracker$ cat HiggsRun1
2019-10-21 10:31:31,203 INFO start listen on 172.16.2.182:9094
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Traceback (most recent call last):
  File "./dmlc-submit", line 9, in <module>
    submit.main()
  File "/home/wendy/xgboost_reproducibility/xgboost/dmlc-core/tracker/dmlc_tracker/submit.py", line 48, in main
    yarn.submit(args)
  File "/home/wendy/xgboost_reproducibility/xgboost/dmlc-core/tracker/dmlc_tracker/yarn.py", line 130, in submit
    pscmd=(' '.join([YARN_BOOT_PY] + args.command)))
  File "/home/wendy/xgboost_reproducibility/xgboost/dmlc-core/tracker/dmlc_tracker/tracker.py", line 423, in submit
    fun_submit(nworker, nserver, envs)
  File "/home/wendy/xgboost_reproducibility/xgboost/dmlc-core/tracker/dmlc_tracker/yarn.py", line 124, in yarn_submit_pass
    submit_thread.append(yarn_submit(args, nworker, nserver, pass_env))
  File "/home/wendy/xgboost_reproducibility/xgboost/dmlc-core/tracker/dmlc_tracker/yarn.py", line 49, in yarn_submit
    out = out.split('\n')[0].split()
TypeError: a bytes-like object is required, not 'str'

**Comment by hcho3** [comment]
@wendycwong Can you review #564? It addresses the same bug and supports both Python 2 and 3.

**Comment by wendycwong** [comment]
Yes, you are right!  That is the same fix.  I approved it.

**Comment by hcho3** [comment]
@wendycwong Thanks for your review. I just merged #564 so closing this one now.

**Pull request closed without merging**
