### PR TITLE
[Windows] Support Visual Studio 2019

### PR DESCRIPTION
**Pull request by vexilligera**
As mentioned in #603

### CODE REVIEW

**Comment by haojin2** [comment]
@szha @tqchen This is the effort for unblocking migration of MXNet windows CI to be using latest VS 2019, please kindly give a review of this when you have time, thanks!

**Comment by hcho3** [comment]
@haojin2 We should add VS 2019 to AppVeyor CI. I can help.

**Comment by hcho3** [comment]
This PR depends on https://github.com/dmlc/dmlc-core/pull/602. Can someone look at it?

**Comment by tqchen** [comment]
Travis CI removed. @hcho3 let us also see if we can move the windows tests to action as well.

**Comment by hcho3** [comment]
I went ahead and added VS 2019 to CI.

**Comment by haojin2** [comment]
@hcho3 @tqchen Thanks for your attention on this!

**Pull request merged**
