### PR TITLE
Platform independent real param parsing

### PR DESCRIPTION
**Pull request by sbodenstein**
This resolves this MXNet issue (https://github.com/dmlc/mxnet/issues/4876). 

@piiswrong

### CODE REVIEW

**Comment by sbodenstein** [comment]
This is failing the lint test, but the file that is failing has not been modified by this PR:
```
src/io/s3_filesys.cc:504:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
```

**Comment by piiswrong** [comment]
Someone merged bad code. Could you fix it?

**Comment by sbodenstein** [comment]
Ok, its passing all the tests now.

**Comment by piiswrong** [comment]
does  std stream correctly print NAN and INF?

**Comment by sbodenstein** [comment]
```
 std::cout << std::stof("inf") << std::endl;
 std::cout << std::stof("-inf") << std::endl;
 std::cout << std::stof("nan") << std::endl;
```
prints to stdout:

```
inf
-inf
nan
```
Is that what you are asking?

**Comment by piiswrong** [comment]
Yeah. LGTM

**Comment by sbodenstein** [comment]
Do I need to make a PR in MXNet to move the commit of the dmlc-core submodule, or will you do that?

**Pull request merged**
