### PR TITLE
Fix memory leak in logging.

### PR DESCRIPTION
**Pull request by trivialfis**

### CODE REVIEW

**Comment by trivialfis** [comment]
@hcho3

**Comment by trivialfis** [comment]
That's new ...
```
 dyld: Symbol not found: ___emutls_get_address
  Referenced from: /usr/local/opt/gcc@8/lib/gcc/8/libstdc++.6.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by tpboudreau** [comment]
@trivialfis: I was tracking down the possibility that this might be a compiler version problem in the macOS 10.15 virtual env -- but it appears that whatever it was, it's been repaired.  Your fix in this branch has been passing all tests in my repo.

You might just want to kick off the github actions script again to see if it's working for you too now.

**Comment by hcho3** [comment]
Root cause for the segfault on 32-bit MinGW: https://sourceforge.net/p/mingw-w64/bugs/527/

**Comment by hcho3** [comment]
@trivialfis I managed to work around the compiler bug. It should now build successfully with the 32-bit MinGW compiler. Can you take a look?

**Comment by hcho3** [comment]
https://ci.appveyor.com/project/tqchen/dmlc-core/builds/37108903/job/jvlw9in5swrxnk83

It appears that thread-local is also broken on 64-bit MinGW

**Comment by hcho3** [comment]
Phew, finally fixed.

**Review by hcho3 — APPROVED** [review]

**Comment by hcho3** [comment]
@junrushao1994 @szha I'd like to get a review from one of you before merging this, as it affects multiple projects.

**Comment by junrushao1994** [comment]
Yeah I have been watching this PR in the recent few days, and surprised by MinGW’s bug...

**Review by junrushao1994 — APPROVED** [review]
LGTM

**Pull request merged**
