### PR TITLE
Fix SetEnv in Windows

### PR DESCRIPTION
**Pull request by ZhennanQin**
As title. Needed by https://github.com/apache/incubator-mxnet/pull/15853
@pengzhao-intel

### CODE REVIEW

**Comment by pengzhao-intel** [comment]
@szha could you help to take a review and merge?

**Comment by szha** [comment]
Could you create a PR that points to your fork of dmlc-core for verification?

**Comment by ZhennanQin** [comment]
https://github.com/apache/incubator-mxnet/pull/15853 is rebased on this change.

**Comment by ZhennanQin** [comment]
https://github.com/apache/incubator-mxnet/pull/16032 is a cleanup PR for verify this PR.

**Comment by ZhennanQin** [comment]
@szha apache/incubator-mxnet#16032 shows this change doesn't break any CI tests for MXNet.

**Pull request merged**
